source 'https://github.com/CocoaPods/Specs.git'
# 增加私有资源库地址
source 'https://gitlab.ad-mex.com/app/Module_iOS.git'
platform :ios, '10.0'

# 消除所有警告
inhibit_all_warnings!

install! 'cocoapods',
# 生成多个 Xcodeproj
:generate_multiple_pod_projects => true,
# 支持增量安装
:incremental_installation => true

target 'MEKSAdapter_Example' do
  pod 'MEKSAdapter', :path => '../'

  target 'MEKSAdapter_Tests' do
    inherit! :search_paths

    
  end
end
